name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        region: us-east-1

    - name: Build Docker Image
      run: |
        IMAGE_TAG=$(date +%s)
        docker build -t ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG .
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Push Docker Image to ECR
      run: |
        docker push ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG

    - name: Update Kubernetes Deployment
      run: |
        kubectl set image deployment/web-app-deployment web-app-container=${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG

    - name: Verify Deployment
      run: |
        kubectl rollout status deployment/web-app-deployment
        kubectl get services
